// <auto-generated />
namespace _14_GeneralStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class idek : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(idek));
        
        string IMigrationMetadata.Id
        {
            get { return "202102241923156_idek"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
